name: 'Grammar and Spelling Review'
description: 'Reviews pull requests for grammar and spelling errors using Chat GPT.'
inputs:
  github-token:
    description: 'GitHub token for API authentication.'
    required: true
  openai-api-key:
    description: 'OpenAI API key for accessing Chat GPT.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.openai-api-key }}
