name: Hello World
on: [push, workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Hello world action step
      uses: ./
      with:
        who-to-greet: 'Mars'
