on: [push, workflow_dispatch]

jobs:
  hello_world:
    runs-on: ubuntu-latest
    name: hello
    steps:
      - name: Checkou repo
        uses: actions/checkout@v2
      - name: Check Grammar and Spelling
        uses: tlofreso/gpt-proofread
        with:
          github-token: "my-token"
          openai-api-key: "my-api-key"
